project_id = "bztjknnilcmfaromieaj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your confirmation code is {{ .Code }}"

[edge_runtime]
enabled = true
inspector_port = 8083
policy = "oneshot"

[functions.sync-google-trends]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.ingest-news]
verify_jwt = true

[cron.jobs]
ingest_news_daily = { schedule = "0 3 * * *", command = "supabase functions invoke ingest-news --no-verify-jwt" }
news_retention_daily = { schedule = "30 3 * * *", command = "supabase functions invoke news-retention --no-verify-jwt" }

[functions.news-retention]
verify_jwt = true